const mongoose = require('mongoose');

const sessionSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true, // fast lookup by user
    },
    topic: {
      type: String,
      required: true,
      trim: true,
    },
    mode: {
      type: String,
      enum: ['report', 'bullets'],
      default: 'report',
    },
    status: {
      type: String,
      enum: ['searching', 'reading', 'summarizing', 'synthesizing', 'done', 'error'],
      default: 'searching',
    },
    queries: {
      type: [String], // search queries generated by Planner Agent
      default: [],
    },
    sources: [
      {
        url: String,
        title: String,
        summary: String, // compressed by Summarizer Agent
      },
    ],
    report: {
      type: String, // final output from Synthesizer Agent
      default: '',
    },
    conflicts: {
      type: [String], // list of detected conflicts between sources
      default: [],
    },
  },
  {
    timestamps: true, // createdAt, updatedAt
  }
);

module.exports = mongoose.model('Session', sessionSchema);
